apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: example
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraCluster
    name: example-provider
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraCluster
metadata:
  name: example-provider
spec:
  user: vagrant
  controlPlaneMachineCount: "1"
  workerMachineCount: "1"
  cri:
    kind: docker
    package: docker-ce
    version: 19.03.8
  kubernetesVersion: 1.18.9
  os:
    files:
    - destination: /etc/yum.repos.d/kubernetes.repo
      source:
        configmap: repo
        contents: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kube*
        key: kubernetes.repo
    - destination: /etc/yum.repos.d/docker-ce.repo
      source:
        configmap: repo
        contents: |
          [docker-ce-stable]
          name=Docker CE Stable - \$basearch
          baseurl=https://download.docker.com/linux/centos/7/\$basearch/stable
          enabled=1
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-stable-debuginfo]
          name=Docker CE Stable - Debuginfo \$basearch
          baseurl=https://download.docker.com/linux/centos/7/debug-\$basearch/stable
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-stable-source]
          name=Docker CE Stable - Sources
          baseurl=https://download.docker.com/linux/centos/7/source/stable
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-edge]
          name=Docker CE Edge - \$basearch
          baseurl=https://download.docker.com/linux/centos/7/\$basearch/edge
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-edge-debuginfo]
          name=Docker CE Edge - Debuginfo \$basearch
          baseurl=https://download.docker.com/linux/centos/7/debug-\$basearch/edge
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-edge-source]
          name=Docker CE Edge - Sources
          baseurl=https://download.docker.com/linux/centos/7/source/edge
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-test]
          name=Docker CE Test - \$basearch
          baseurl=https://download.docker.com/linux/centos/7/\$basearch/test
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-test-debuginfo]
          name=Docker CE Test - Debuginfo \$basearch
          baseurl=https://download.docker.com/linux/centos/7/debug-\$basearch/test
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-test-source]
          name=Docker CE Test - Sources
          baseurl=https://download.docker.com/linux/centos/7/source/test
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-nightly]
          name=Docker CE Nightly - \$basearch
          baseurl=https://download.docker.com/linux/centos/7/\$basearch/nightly
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-nightly-debuginfo]
          name=Docker CE Nightly - Debuginfo \$basearch
          baseurl=https://download.docker.com/linux/centos/7/debug-\$basearch/nightly
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg

          [docker-ce-nightly-source]
          name=Docker CE Nightly - Sources
          baseurl=https://download.docker.com/linux/centos/7/source/nightly
          enabled=0
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg
        key: docker-ce.repo
    - destination: /tmp/cloud-google-com.gpg.b64
      source:
        configmap: repo
        contents: |
          xsBNBF/Jfl4BCADTPUXdkNu057X+P3STVxCzJpU2Mn+tUamKdSdVambGeYFINcp/EGwNGhdb0a1B
          bHs1SWYZbzwh4d6+p3k4ABzVMO+RpMu/aBx9E5aOn5c8GzHjZ/VEaheqLLhSUcSCzChSZcN5jz0h
          TGhmAGaviMt6RMzSfbIhZPj1kDzBiGd0Qwd/rOPnJr4taPruR3ecBjhHti1/BMGd/lj0F7zQnCjp
          7PrqgpEPBT8jo9wX2wvOyXswSI/GsfbFiaOJfDnYengaEg8sF+u3WOs0Z20cSr6kS76KHpTfa3Jj
          YsfHt8NDw8w4e3H8PwQzNiRP9tXeMASKQz3emMj/ek6HxjihY9qFABEBAAHNumdMaW51eCBSYXB0
          dXJlIEF1dG9tYXRpYyBTaWduaW5nIEtleSAoLy9kZXBvdC9nb29nbGUzL3Byb2R1Y3Rpb24vYm9y
          Zy9jbG91ZC1yYXB0dXJlL2tleXMvY2xvdWQtcmFwdHVyZS1wdWJrZXlzL2Nsb3VkLXJhcHR1cmUt
          c2lnbmluZy1rZXktMjAyMC0xMi0wMy0xNl8wOF8wNS5wdWIpIDxnbGludXgtdGVhbUBnb29nbGUu
          Y29tPsLAaAQTAQgAHAUCX8l+XgkQi1fFwoNvS+sCGwMFCQPDCrACGQEAAEF6CACaekro6aUJJd3m
          VtrtLOOewV8et1jep5ewmpOrew/pajRVBeIbV1awVn0/8EcenFejmP6WFcdCWouDVIS/QmRFQV9N
          6YXN8PiwalrRV3bTKFBHkwa1cEH4AafCGo0cDvJb8N3JnM/Rmb1KSGKr7ZXpmkLtYVqr6Hgzl+sn
          rlH0Xwsl5r3SyvqBgvRYTQKZpKqmBEd1udieVoLSF988kKeNDjFa+Q1SjZPGW+XukgE8kBUbSDx8
          Y8q6Cszh3VVY+5JUeqimRgJ2ADY2/3lEtAZOtmwcBlhY0cPWVqga14E7kTGSWKC6W96Nfy9K7L4Y
          pp8nTMErus181aqwwNfMqnpnzsBNBF/Jfl4BCADDSh+KdBeNjIclVVnRKt0QT5593yF4WVZt/TgN
          uaEZ5vKknooVVIq+cJIfY/3lUqq8Te4dEjodtFyKe5Xuego6qjzs8TYFdCAHXpXRoUolT14m+qkJ
          8rhSrpN0TxIjWJbJdm3NlrgTam5RKJw3ShypNUxyolnHelXxqyKDCkxBSDmR6xcdft3wdQl5IkIA
          wxe6nywmSUtpndGLRJdJraJiaWF2IBjFNg3vTEYj4eoehZd4XrvEyLVrMbKZ5m6f1o6QURuzSrUH
          9JT/ivZqCmhPposClXXX0bbi9K0Z/+uVyk6v76ms3O50rIq0L0YehM8G++qmGO421+0qCLkdD5/j
          ABEBAAHCwF8EGAEIABMFAl/Jfl4JEItXxcKDb0vrAhsMAAAbGggAw7lhSWElZpGV1SI2b2K26PB9
          3fVI1tQYV37WIElCJsajF+/ZDfJJ2d6ncuQSleH5WRccc4hZfKwysA/epqrCnwc7yKsToZ4sw8xs
          JF1UtQ5ENtkdArViBJHS4Y2VZ5DEUmr5EghGtZFh9a6aLoeMVM/nrZCLstDVoPKEpLokHu/gebCw
          fT/n9U1dolFIovg6eKACl5xOx+rzcAVp7R4P527jffudz3dKMdLhPrstG0w5YbyfPPwWMOPp+kUF
          45eYdR7kKKk09VrJNkEGJ0KQQ6imqR1Tn0kyu4cvkfqnCUF0rrn7CdBqLSCv1QRhgr6TChQf7ynW
          sPz5gGdVjh3tI8bATQRgPRBZAQgAtYpc0k9MJ7PrsGchAOSFbWHsgLl02kFBAHe9EqiJUKQ3eBMl
          Ysd0gmp0CLvHRvWat/sdvFgW9jrlz/aHNOsmzlnbtpuzeT2NAVE+AjgN+iVf2K8ZjbPufzPmJwx6
          ab+t44ESDpM181zaOksE7JdsRvXygd00tCDLwZFncOTxqwTORoIUXHnIKEgAMEW1iVzkRxilcJVe
          rTsUGf8agNPITyZ3jH7DBTzl7IrYBkR6F45VFi1Xie9JpiGLAv6QYJSMAs5nQ/BHt/TK5Ul27l1U
          Is9/Ih35712KSxJoDVysyNAx/bSoPN9t5AC86miZSxTiyZv7lSV0VBHykty4VWUDMwARAQABzVFS
          YXB0dXJlIEF1dG9tYXRpYyBTaWduaW5nIEtleSAoY2xvdWQtcmFwdHVyZS1zaWduaW5nLWtleS0y
          MDIxLTAzLTAxLTA4XzAxXzA5LnB1YinCwGgEEwEIABwFAmA9EFkJEP7qkWkwfqBxAhsDBQkDwwqw
          AhkBAAB7ZQgAsUljKd8kXC5rB4cRg7efZ4UjV4aLlojXj0jHubxE0AP5YYqfWcfzT0QmuKuY6SAw
          ZRGDoOu2Gp87XI0lhkiN+V25auNx+Li0sYeD7Ss2TKPlI/J9lTRzmVwXRnLDg3FN8pxeuK+3k0Hr
          1HtmlNCjdqOuejtx6xOIrTlSmMJ55JjbJBuOW/W+wyZ7EOlj7M1HPJTYbGtoASOr3y5evL44+z5V
          sNN9ATP0aDBD6aDgKaIR6LH5zYcSZhNQMcAZDBM8qNpGYT2RofOSw5w2wL40hSqmEj0XipkRYy5a
          Nwz1R2f3XkJ+p6B24FAoS6NtRXn4ZWTurcrK29vNzFjCMmP2Es7ATQRgPRBZAQgA3HTvwMNarnWT
          kWQjS89704kEhXFBWMknHySZ8FLIPH8tJIIPaJRWNBiuYnE+p/7IXNUZSKbqqzkGAWYLSt3UmXzg
          FxNjdtB1Lwvp6yirl11/o3DP19ZB8cF+bRunwdX8jR9Kf0KrMxH2ERybtGOD6J02CLJSE5xM5TeI
          VDev5sdfplj5eD+Ee/4evqe0No7WgpRLXXRdHnjn9ejGuUvH33/NLmQiyaFbt5Tlwk9tqAn+6ph9
          l3XZqhorFEnKsJm5rr99LXUHnZ/vJ4yqNqX6VRdTmuuwlkV3Sk5J7mcm8SPSKXIr8vAiEi9g6NLs
          4o+0ke5HlX+xtUNyt4idMJ+pgwARAQABwsBfBBgBCAATBQJgPRBZCRD+6pFpMH6gcQIbDAAAP9wI
          ABSdoRKdteOH84LTVhzlRb9u4bKzu8GBWcKInPZR0peIhMPJiXP95BF3YPVX/Ztc2xv5GerJZs6X
          7+8wwHTd4dx09Adcq298V80V9M4TmAG0ElJ3Og3poQ2aA1rf8FXHin873mwfVUw80QVFc8Qnbr2O
          oo9KdgD2aZ06857wj6Ah5H8wTAt2cpNRbnoj0z6D9fTNAT66DMvKg1UpBa9Ll9zzOeIUDephkUIO
          R1VQcVDWjJ59sjkHMW0P0/3SpaI3aUZr6RsmI3678hMRPKMGJ/C+5ctje+hnGOpIjdQpk5woHa21
          NEj2nJu128U2JUB8CQhGvR3+P57ogWscFyrnP8s=
        key: cloud-google-com.gpg.b64
    - destination: /etc/docker/daemon.json
      source:
        configmap: docker
        contents: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "exec-opts": [
              "native.cgroupdriver=cgroupfs"
            ]
          }
        key: daemon.json
