before:
  hooks:
    - go mod download
builds:
- id: wksctl
  main: ./cmd/wksctl
  binary: wksctl
  ldflags:
    - -X github.com/weaveworks/wksctl/pkg/version.Version={{.Version}}
    - -X github.com/weaveworks/wksctl/pkg/version.ImageTag={{.Env.IMAGE_TAG}}
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goarch:
    - amd64
  hooks:
    pre: make generated
archives:
  - name_template: "wksctl-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      386: i386
      amd64: x86_64
    files:
      - examples/**/*
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
