site_name: wksctl
site_description: Weave Kubernetes System Control
site_author: wksctl developer community
site_url: https://wksctl.readthedocs.io

# Repository
repo_name: weaveworks/wksctl
repo_url: https://github.com/weaveworks/wksctl
edit_uri: ""

theme:
  name: material
  logo: _static/logo.svg
  language: en
  feature:
    tabs: false
  palette:
    primary: blue
    accent: indigo
  highlightjs: true

docs_dir: docs

extra_css:
  - _static/custom.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - toc:
      permalink: true
