apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: example
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraCluster
    name: example-provider
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraCluster
metadata:
  name: example-provider
spec:
  cri:
    kind: docker
    package: docker-ce
    version: 19.03.8
  os:
    files:
    - destination: /etc/yum.repos.d/kubernetes.repo
      source:
        configmap: repo
        key: kubernetes.repo
    - destination: /etc/yum.repos.d/docker-ce.repo
      source:
        configmap: repo
        key: docker-ce.repo
    - destination: /tmp/cloud-google-com.gpg.b64
      source:
        configmap: repo
        key: cloud-google-com.gpg.b64
  user: root