apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: master
  name: master-1
spec:
  clusterName: example
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: master-1
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: master-1
spec:
  private:
    address: 172.17.0.2
    port: 22
  public:
    address: 127.0.0.1
    port: 2222
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: master
  name: master-2
spec:
  clusterName: example
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: master-2
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: master-2
spec:
  private:
    address: 172.17.0.3
    port: 22
  public:
    address: 127.0.0.1
    port: 2223
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: master
  name: master-3
spec:
  clusterName: example
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: master-3
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: master-3
spec:
  private:
    address: 172.17.0.4
    port: 22
  public:
    address: 127.0.0.1
    port: 2224
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: worker
  name: worker-1
spec:
  clusterName: example
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: worker-1
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: worker-1
spec:
  private:
    address: 172.17.0.5
    port: 22
  public:
    address: 127.0.0.1
    port: 2225